[package]
name = "rust-jemalloc-pprof-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jemalloc_pprof = { path = ".." }
tokio = { version = "1", features = ["full"] }
axum = "0.8.9"
[target.'cfg(all(not(target_env = "msvc"), not(target_os = "macos")))'.dependencies]
tikv-jemallocator = { version = "0.7", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms", "background_threads"] }

[target.'cfg(all(not(target_env = "msvc"), target_os = "macos"))'.dependencies]
tikv-jemallocator = { version = "0.7", features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms"] }

[features]
flamegraph = ["jemalloc_pprof/flamegraph"]
