[package]
name = "rust-jemalloc-pprof-example"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
jemalloc_pprof = { workspace = true }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true }
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, features = ["profiling", "stats", "unprefixed_malloc_on_supported_platforms", "background_threads"] }

[features]
flamegraph = ["jemalloc_pprof/flamegraph"]
