[workspace]
members = ["mappings", "capi", "util", "example"]

[package]
name = "jemalloc_pprof"
description = "Convert jemalloc heap profiles to pprof to understand memory usage, fix memory leaks, and fix OOM Kills."
version.workspace = true
edition.workspace = true
publish = true
license.workspace = true
authors = [
    "Frederic Branczyk <frederic.branczyk@polarsignals.com>",
    "Brennan Vincent <brennan.vincent@polarsignals.com>",
]
repository.workspace = true
keywords = ["jemalloc", "pprof", "memory", "profiling", "observability"]
categories = [
    "development-tools",
    "development-tools::profiling",
    "development-tools::debugging",
    "memory-management",
]
documentation = "https://docs.rs/jemalloc_pprof/latest/jemalloc_pprof/"
homepage = "https://crates.io/crates/jemalloc_pprof"

[package.metadata.docs.rs]
all-features = true

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/polarsignals/rust-jemalloc-pprof"
version = "0.9.0"

[workspace.dependencies]
jemalloc_pprof = { path = ".", version = "0.9.0" }
pprof_util = { path = "./util", version = "0.9.0" }
mappings = { path = "./mappings", version = "0.9.0" }
anyhow = "1"
axum = "0.8.9"
backtrace = "0.3"
errno = "0.3"
flate2 = "1.1"
inferno = "0.12"
libc = "0.2"
num = "0.4"
once_cell = "1.21"
paste = "1.0"
prost = { version = "0.14", features = ["no-recursion-limit"] }
tempfile = "3.27"
tikv-jemallocator = { version = "0.7" }
tikv-jemalloc-ctl = { version = "0.7", features = ["use_std"] }
tracing = "0.1"
tokio = { version = "1", features = ["time", "sync"] }

[dependencies]
pprof_util.workspace = true
mappings.workspace = true
libc.workspace = true
anyhow.workspace = true
tikv-jemalloc-ctl.workspace = true
once_cell.workspace = true
tracing.workspace = true
tempfile.workspace = true
tokio.workspace = true

[features]
flamegraph = ["pprof_util/flamegraph"]
symbolize = ["pprof_util/symbolize"]

[dev-dependencies]
# re-import tokio to enable all its features. This is required to
# successfully compile the test snipptes that are part of the documentation
tokio = { workspace = true, features = ["full"] }
tikv-jemallocator = { workspace = true }
axum = { workspace = true }
