[package]
name = "pprof_util"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "various utilities for representing and manipulating profiling data"
publish = true
homepage = "https://crates.io/crates/pprof_util"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2.workspace = true
prost.workspace = true
anyhow.workspace = true
num.workspace = true
paste.workspace = true
backtrace = { workspace = true, optional = true }
inferno = { workspace = true, optional = true }

[features]
flamegraph = ["symbolize", "dep:inferno"]
symbolize = ["dep:backtrace"]
